apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: app-public
          emptyDir: {}

        - name: app-storage
          {{- if .Values.persistence }}
          hostPath:
            path: /data/eventix/app
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}

        - name: nginx-config
          configMap:
            name: nginx-config

        - name: php-config
          configMap:
            name: php-config
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          ports:
            - name: http
              containerPort: 3200
          volumeMounts:
            - name: app-public
              mountPath: /var/www/public
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20

        - name: app
          image: {{ include "chart.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /var/www/storage/app/public &&
              cp -a /var/www/public/. /mnt/public/ &&
              exec php-fpm -F
          ports:
            - name: fpm
              containerPort: 9000
          volumeMounts:
            - name: app-public
              mountPath: /mnt/public
            - name: app-storage
              mountPath: /var/www/storage/app
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/z-custom.ini
              subPath: php.ini
              readOnly: true
            - name: php-config
              mountPath: /usr/local/etc/php-fpm.d/z-www.conf
              subPath: php-fpm.conf
              readOnly: true
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: secrets
          readinessProbe:
            tcpSocket:
              port: fpm
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: fpm
            initialDelaySeconds: 15
            periodSeconds: 20
