apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    app: migrate
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: { { include "chart.image" . } }
          imagePullPolicy: { { .Values.image.pullPolicy } }
          command:
            - sh
            - -c
            - |
              php artisan migrate --force {{- if and .Values.db .Values.db.seed }} && \
              php artisan db:seed --force {{- end }}
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: secrets
