{{- if .Values.secrets.remote_secret_name }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets
  labels:
    app: web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.remote_secret_name }}

{{- else }}

apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
{{- .Values.secrets | toYaml | nindent 2 }}

{{- end }}
