x-common-php: &common-php
    build:
        context: .
        dockerfile: ./deploy/Dockerfile
    volumes:
        - .:/var/www
        - shared-files:/var/www/public
    environment:
        APP_URL: http://localhost:3200
        APP_ENV: production

        DB_HOST: host.docker.internal
        DB_PORT: 3306
        DB_DATABASE: eventix
        DB_USERNAME: root
        DB_PASSWORD:

services:
    php:
        <<: *common-php

    scheduler:
        <<: *common-php
        entrypoint: ["php", "artisan", "schedule:work"]

    queue:
        <<: *common-php
        entrypoint: ["php", "artisan", "queue:work"]

    nginx:
        image: nginx:latest
        ports:
            - 3200:3200
        volumes:
            - ./deploy/files/nginx.conf:/etc/nginx/nginx.conf
            - shared-files:/var/www/public
        depends_on:
            - php

volumes:
    shared-files:
