services:
    app:
        build:
            context: .
            dockerfile: deploy/Dockerfile
        environment:
            APP_URL: http://localhost:3200
            APP_ENV: production

        ports:
            - "3200:3200"
