domain: eventix.k8s.test

image:
  repository: rdzpedraos/eventix
  tag: ""
  pullPolicy: IfNotPresent

nginx:
  image: nginx:1.27-alpine

db:
  enabled: false
  seed: false
  image: mysql:8.0

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

resources:
  nginx:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  app:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

scheduler:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300

secrets:
  remote_secret_name: SECRETS-k8s

configMap:
  APP_NAME: Eventix
  APP_ENV: production
  APP_DEBUG: "false"
  APP_TIMEZONE: UTC
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US
  APP_MAINTENANCE_DRIVER: file

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: stack
  LOG_STACK: single
  LOG_LEVEL: info

  DB_CONNECTION: mysql

  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"

  BROADCAST_CONNECTION: log
  FILESYSTEM_DISK: local

  QUEUE_CONNECTION: database
  CACHE_STORE: database

  MAIL_MAILER: log
  MAIL_FROM_NAME: Eventix
