domain: eventix.k8s.test

secrets:
  APP_KEY: "base64:e7QhiVhXyxLfLaDK1vZ6FOU4GwI0QvWX7t7r8TW7uGI="

  DB_HOST: host.minikube.internal
  DB_PORT: "3306"
  DB_DATABASE: eventix
  DB_USERNAME: admin
  DB_PASSWORD: dev

  MAIL_HOST: ""
  MAIL_PORT: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: ""
