autoscaling:
  enabled: false

persistence: false

db:
  enabled: true

secrets:
  remote_secret_name: ""

  # APP_KEY fixed for ephemeral previews (not production).
  APP_KEY: "base64:ePbfuu8V1ehrN2StH6lpAGViahaFMMd1C3b9sYnLnqY="

  DB_DATABASE: eventix
  DB_USERNAME: eventix
  DB_PASSWORD: root

configMap:
  APP_ENV: local
  APP_DEBUG: "true"
  MAIL_MAILER: log
