notifications:
  enabled: true

  notifiers:
    service.github: |
      token: $github-token

  triggers:
    on-deployed: |
      - oncePer: app.status.operationState.syncResult.revision
        send:
          - preview-deployed
        when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    on-sync-failed: |
      - oncePer: app.status.operationState.syncResult.revision
        send:
          - preview-failed
        when: app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed']
    on-health-degraded: |
      - oncePer: app.status.operationState.syncResult.revision
        send:
          - preview-failed
        when: app.status.health.status == 'Degraded'

  templates:
    preview-deployed: |
      github:
        repoURLPath: "{{.app.spec.source.repoURL}}"
        revisionPath: "{{.app.status.operationState.syncResult.revision}}"
        pullRequestComment:
          commentTag: "preview/{{.app.metadata.name}}"
          content: |
            🚀 Proyecto desplegado 
            🔗 {{index .app.metadata.annotations "preview-url"}}
    preview-failed: |
      github:
        repoURLPath: "{{.app.spec.source.repoURL}}"
        revisionPath: "{{.app.status.operationState.syncResult.revision}}"
        pullRequestComment:
          commentTag: "preview/{{.app.metadata.name}}"
          content: |
            🚨 No se pudo desplegar el proyecto 🚨
