notifications:
  enabled: true

  secret:
    create: false

  notifiers:
    service.github: |
      appID: $githubAppID
      installationID: $githubAppInstallationID
      privateKey: $githubAppPrivateKey

  triggers:
    trigger.on-deployed: |
      - oncePer: app.status.sync.revision
        send:
          - preview-deployed
        when: app.status.sync.status == 'Synced' and app.status.health.status == 'Healthy'
    trigger.on-sync-failed: |
      - oncePer: app.status.sync.revision
        send:
          - preview-failed
        when: app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed']
    trigger.on-health-degraded: |
      - oncePer: app.status.sync.revision
        send:
          - preview-failed
        when: app.status.health.status == 'Degraded'

  templates:
    template.preview-deployed: |
      github:
        pullRequestComment:
          commentTag: "preview/{{.app.metadata.name}}"
          content: |
            🚀 Proyecto desplegado
            🔗 {{index .app.metadata.annotations "preview-url"}}
    template.preview-failed: |
      github:
        pullRequestComment:
          commentTag: "preview/{{.app.metadata.name}}"
          content: |
            🚨 No se pudo desplegar el proyecto 🚨
