name: Preview cleanup

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete Argo PR comments
        uses: ./.github/actions/delete-argo-pr-comments
