name: Preview cleanup

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

env:
  ARGO_NOTIFICATIONS_BOT: despliegaloargocd[bot]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        env:
          ARGO_NOTIFICATIONS_BOT: ${{ env.ARGO_NOTIFICATIONS_BOT }}
        with:
          script: |
            const pr = context.issue.number;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              per_page: 100,
            });

            comments.filter(
              (comment) => comment.user?.login === process.env.ARGO_NOTIFICATIONS_BOT,
            ).forEach(async (comment) => {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              });
            });
